server:
  port: 8080


spring:
  kafka:
    bootstrap-servers: 192.168.64.4:9092,192.168.64.4:9093,192.168.64.4:9094
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: default-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 500
    listener:
      # 当每一条记录被消费者监听器 (Listenerconsumer）处理之后提交
      #RECORD
      # 当每一批po11（)的数据被消费者监听器 (Listenerconsumer）处理之后提交
      #BATCH
      # 当每一批poLI()的数据被消费者监听器 (Listenerconsumer）处理之后，距离上次提交时间大于TIME时提交
      # TIME
      # 当每一批poLI()的数据被消费者监听器 (Listenerconsumer）处理之后，被处理record数量大于等于COUNT时提交
      # COUNT
      #TIME / COUNT 有一个条件满足时提交
      # CQUNT_TIME
      # 当每一批pOII()的数据被消费者监听器 (Listenerconsumer）处理之后，手动调用Acknowledgment.acknowledge()后提交
      # MANUAL
      # 手动调用Acknowledgment.acknowledge()后立即提交，一般使用这种
      # MANUAL_INMEDIATE
      ack-mode: manual_immediate